# Generated by Django 4.0.3 on 2022-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djresume', '0002_userprofile_age_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Bangladesh', max_length=120),
        ),
    ]
