# Generated by Django 4.0.3 on 2022-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djresume', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
