# Generated by Django 4.0.3 on 2022-03-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djresume', '0006_projectcategory_projectstack_userprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year_start', models.CharField(max_length=4)),
                ('year_end', models.CharField(blank=True, max_length=4, null=True)),
                ('is_year_present', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('year_start', models.CharField(max_length=4)),
                ('year_end', models.CharField(blank=True, max_length=4, null=True)),
                ('is_year_present', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
