# Generated by Django 4.0.3 on 2022-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djresume', '0007_education_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employment',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
